/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/token/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obtain Token */
        post: operations["token_obtain_pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["token_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Token */
        post: operations["token_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/sucursales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sucursales */
        get: operations["core_api_list_sucursales"];
        put?: never;
        /** Create Sucursal */
        post: operations["core_api_create_sucursal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/sucursales/{sucursal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sucursal */
        get: operations["core_api_get_sucursal"];
        /** Update Sucursal */
        put: operations["core_api_update_sucursal"];
        post?: never;
        /** Delete Sucursal */
        delete: operations["core_api_delete_sucursal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personas */
        get: operations["core_api_list_personas"];
        put?: never;
        /** Create Persona */
        post: operations["core_api_create_persona"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Persona */
        get: operations["core_api_get_persona"];
        /** Update Persona */
        put: operations["core_api_update_persona"];
        post?: never;
        /** Delete Persona */
        delete: operations["core_api_delete_persona"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/marcas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Marcas */
        get: operations["catalog_api_list_marcas"];
        put?: never;
        /** Create Marca */
        post: operations["catalog_api_create_marca"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/marcas/{marca_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Marca */
        get: operations["catalog_api_get_marca"];
        put?: never;
        post?: never;
        /** Delete Marca */
        delete: operations["catalog_api_delete_marca"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categorias */
        get: operations["catalog_api_list_categorias"];
        put?: never;
        /** Create Categoria */
        post: operations["catalog_api_create_categoria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categorias/{cat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Categoria */
        get: operations["catalog_api_get_categoria"];
        put?: never;
        post?: never;
        /** Delete Categoria */
        delete: operations["catalog_api_delete_categoria"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/sabores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sabores */
        get: operations["catalog_api_list_sabores"];
        put?: never;
        /** Create Sabor */
        post: operations["catalog_api_create_sabor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/sabores/{sabor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sabor */
        get: operations["catalog_api_get_sabor"];
        put?: never;
        post?: never;
        /** Delete Sabor */
        delete: operations["catalog_api_delete_sabor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Productos */
        get: operations["catalog_api_list_productos"];
        put?: never;
        /** Create Producto */
        post: operations["catalog_api_create_producto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/productos/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Producto */
        get: operations["catalog_api_get_producto"];
        /** Update Producto */
        put: operations["catalog_api_update_producto"];
        post?: never;
        /** Delete Producto */
        delete: operations["catalog_api_delete_producto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/productos/buscar-por-codigo/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search By Barcode */
        get: operations["catalog_api_search_by_barcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/codigos-barra/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Codigos Barra */
        get: operations["catalog_api_list_codigos_barra"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/codigos-barra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Codigo Barra */
        post: operations["catalog_api_create_codigo_barra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/codigos-barra/{codigo_barra_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Codigo Barra */
        delete: operations["catalog_api_delete_codigo_barra"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/stock/{sucursal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stock By Sucursal */
        get: operations["inventory_api_list_stock_by_sucursal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Or Update Stock */
        post: operations["inventory_api_create_or_update_stock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/stock/{stock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Stock */
        put: operations["inventory_api_update_stock"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/traslados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Traslados */
        get: operations["inventory_api_list_traslados"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/traslados/{traslado_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Traslado */
        get: operations["inventory_api_get_traslado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/traslados/enviar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar Traslado */
        post: operations["inventory_api_enviar_traslado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/traslados/{traslado_id}/recibir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recibir Traslado */
        post: operations["inventory_api_recibir_traslado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/timbrados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Timbrados */
        get: operations["billing_api_list_timbrados"];
        put?: never;
        /** Create Timbrado */
        post: operations["billing_api_create_timbrado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/timbrados/{timbrado_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timbrado */
        get: operations["billing_api_get_timbrado"];
        /** Update Timbrado */
        put: operations["billing_api_update_timbrado"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Turnos */
        get: operations["pos_api_list_turnos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/turnos/{turno_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Turno */
        get: operations["pos_api_get_turno"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/turnos/abrir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abrir Turno */
        post: operations["pos_api_abrir_turno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/turnos/{turno_id}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar Turno */
        post: operations["pos_api_cerrar_turno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/ventas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ventas */
        get: operations["pos_api_list_ventas"];
        put?: never;
        /** Crear Venta */
        post: operations["pos_api_crear_venta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/ventas/{venta_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Venta */
        get: operations["pos_api_get_venta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/ventas/{venta_id}/anular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anular Venta */
        post: operations["pos_api_anular_venta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/movimientos/{turno_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movimientos */
        get: operations["pos_api_list_movimientos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pos/movimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Movimiento */
        post: operations["pos_api_create_movimiento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logistics/compras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Compras */
        get: operations["logistics_api_list_compras"];
        put?: never;
        /** Crear Compra */
        post: operations["logistics_api_crear_compra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logistics/compras/{compra_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Compra */
        get: operations["logistics_api_get_compra"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** TokenObtainPairOutputSchema */
        TokenObtainPairOutputSchema: {
            /**
             * Nombre De Usuario
             * @description Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
             */
            username: string;
            /** Refresh */
            refresh: string;
            /** Access */
            access: string;
        };
        /** TokenObtainPairInputSchema */
        TokenObtainPairInputSchema: {
            /** Contraseña */
            password: string;
            /**
             * Nombre De Usuario
             * @description Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
             */
            username: string;
        };
        /** TokenRefreshOutputSchema */
        TokenRefreshOutputSchema: {
            /** Refresh */
            refresh: string;
            /** Access */
            access: string | null;
        };
        /** TokenRefreshInputSchema */
        TokenRefreshInputSchema: {
            /** Refresh */
            refresh: string;
        };
        /** Schema */
        Schema: Record<string, never>;
        /** TokenVerifyInputSchema */
        TokenVerifyInputSchema: {
            /** Token */
            token: string;
        };
        /** SucursalOut */
        SucursalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Direccion */
            direccion: string;
            /** Es Central */
            es_central: boolean;
            /** Activo */
            activo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SucursalIn */
        SucursalIn: {
            /** Nombre */
            nombre: string;
            /**
             * Direccion
             * @default
             */
            direccion: string;
            /**
             * Es Central
             * @default false
             */
            es_central: boolean;
            /**
             * Activo
             * @default true
             */
            activo: boolean;
        };
        /** SucursalUpdate */
        SucursalUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Es Central */
            es_central?: boolean | null;
            /** Activo */
            activo?: boolean | null;
        };
        /** PersonaOut */
        PersonaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Cedula Ruc */
            cedula_ruc: string;
            /** Dv */
            dv: number | null;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /** Razon Social */
            razon_social: string;
            /** Direccion */
            direccion: string;
            /** Telefono */
            telefono: string;
            /** Email */
            email: string;
            /** Es Cliente */
            es_cliente: boolean;
            /** Es Proveedor */
            es_proveedor: boolean;
            /** User Id */
            user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PersonaIn */
        PersonaIn: {
            /** Cedula Ruc */
            cedula_ruc: string;
            /** Dv */
            dv?: number | null;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /**
             * Razon Social
             * @default
             */
            razon_social: string;
            /**
             * Direccion
             * @default
             */
            direccion: string;
            /**
             * Telefono
             * @default
             */
            telefono: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Es Cliente
             * @default false
             */
            es_cliente: boolean;
            /**
             * Es Proveedor
             * @default false
             */
            es_proveedor: boolean;
            /** User Id */
            user_id?: number | null;
        };
        /** PersonaUpdate */
        PersonaUpdate: {
            /** Cedula Ruc */
            cedula_ruc?: string | null;
            /** Dv */
            dv?: number | null;
            /** Nombre */
            nombre?: string | null;
            /** Apellido */
            apellido?: string | null;
            /** Razon Social */
            razon_social?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Es Cliente */
            es_cliente?: boolean | null;
            /** Es Proveedor */
            es_proveedor?: boolean | null;
            /** User Id */
            user_id?: number | null;
        };
        /** MarcaOut */
        MarcaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MarcaIn */
        MarcaIn: {
            /** Nombre */
            nombre: string;
        };
        /** CategoriaOut */
        CategoriaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CategoriaIn */
        CategoriaIn: {
            /** Nombre */
            nombre: string;
        };
        /** SaborOut */
        SaborOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SaborIn */
        SaborIn: {
            /**
             * Nombre
             * @default
             */
            nombre: string;
        };
        /** ProductoOut */
        ProductoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Base */
            nombre_base: string;
            /**
             * Marca Id
             * Format: uuid
             */
            marca_id: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Sabor Id */
            sabor_id: string | null;
            /** Peso Presentacion */
            peso_presentacion: string;
            /** Unidad Medida */
            unidad_medida: string;
            /** Precio Costo Promedio */
            precio_costo_promedio: string;
            /** Precio Venta */
            precio_venta: string;
            /** Activo */
            activo: boolean;
            /** Atributos Extra */
            atributos_extra: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductoIn */
        ProductoIn: {
            /** Nombre Base */
            nombre_base: string;
            /**
             * Marca Id
             * Format: uuid
             */
            marca_id: string;
            /**
             * Categoria Id
             * Format: uuid
             */
            categoria_id: string;
            /** Sabor Id */
            sabor_id?: string | null;
            /** Peso Presentacion */
            peso_presentacion: number | string;
            /** Unidad Medida */
            unidad_medida: string;
            /**
             * Precio Costo Promedio
             * @default 0
             */
            precio_costo_promedio: number | string;
            /** Precio Venta */
            precio_venta: number | string;
            /**
             * Activo
             * @default true
             */
            activo: boolean;
            /** Atributos Extra */
            atributos_extra?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProductoUpdate */
        ProductoUpdate: {
            /** Nombre Base */
            nombre_base?: string | null;
            /** Marca Id */
            marca_id?: string | null;
            /** Categoria Id */
            categoria_id?: string | null;
            /** Sabor Id */
            sabor_id?: string | null;
            /** Peso Presentacion */
            peso_presentacion?: number | string | null;
            /** Unidad Medida */
            unidad_medida?: string | null;
            /** Precio Venta */
            precio_venta?: number | string | null;
            /** Activo */
            activo?: boolean | null;
            /** Atributos Extra */
            atributos_extra?: {
                [key: string]: unknown;
            } | null;
        };
        /** CodigoBarraOut */
        CodigoBarraOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Codigo */
            codigo: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CodigoBarraIn */
        CodigoBarraIn: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Codigo */
            codigo: string;
        };
        /** StockSucursalOut */
        StockSucursalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sucursal Id
             * Format: uuid
             */
            sucursal_id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad Actual */
            cantidad_actual: string;
            /** Stock Minimo */
            stock_minimo: string;
            /** Punto Pedido */
            punto_pedido: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StockSucursalIn */
        StockSucursalIn: {
            /**
             * Sucursal Id
             * Format: uuid
             */
            sucursal_id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /**
             * Cantidad Actual
             * @default 0
             */
            cantidad_actual: number | string;
            /**
             * Stock Minimo
             * @default 2
             */
            stock_minimo: number | string;
            /**
             * Punto Pedido
             * @default 5
             */
            punto_pedido: number | string;
        };
        /** StockSucursalUpdate */
        StockSucursalUpdate: {
            /** Cantidad Actual */
            cantidad_actual?: number | string | null;
            /** Stock Minimo */
            stock_minimo?: number | string | null;
            /** Punto Pedido */
            punto_pedido?: number | string | null;
        };
        /** DetalleTrasladoOut */
        DetalleTrasladoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad Enviada */
            cantidad_enviada: string;
            /** Cantidad Recibida */
            cantidad_recibida: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TrasladoOut */
        TrasladoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sucursal Origen Id
             * Format: uuid
             */
            sucursal_origen_id: string;
            /**
             * Sucursal Destino Id
             * Format: uuid
             */
            sucursal_destino_id: string;
            /** Usuario Emisor Id */
            usuario_emisor_id: number;
            /** Usuario Receptor Id */
            usuario_receptor_id: number | null;
            /** Estado */
            estado: string;
            /** Fecha Envio */
            fecha_envio: string | null;
            /** Fecha Recepcion */
            fecha_recepcion: string | null;
            /** Detalles */
            detalles: components["schemas"]["DetalleTrasladoOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DetalleTrasladoIn */
        DetalleTrasladoIn: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad Enviada */
            cantidad_enviada: number | string;
        };
        /** TrasladoIn */
        TrasladoIn: {
            /**
             * Sucursal Origen Id
             * Format: uuid
             */
            sucursal_origen_id: string;
            /**
             * Sucursal Destino Id
             * Format: uuid
             */
            sucursal_destino_id: string;
            /** Detalles */
            detalles: components["schemas"]["DetalleTrasladoIn"][];
        };
        /** TrasladoRecepcionIn */
        TrasladoRecepcionIn: {
            /** Items */
            items: components["schemas"]["TrasladoRecepcionItem"][];
        };
        /** TrasladoRecepcionItem */
        TrasladoRecepcionItem: {
            /**
             * Detalle Id
             * Format: uuid
             */
            detalle_id: string;
            /** Cantidad Recibida */
            cantidad_recibida: number | string;
        };
        /** TimbradoEmisionOut */
        TimbradoEmisionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sucursal Id
             * Format: uuid
             */
            sucursal_id: string;
            /** Numero Timbrado */
            numero_timbrado: string;
            /** Punto Establecimiento */
            punto_establecimiento: string;
            /** Punto Expedicion */
            punto_expedicion: string;
            /** Fecha Inicio Vigencia */
            fecha_inicio_vigencia: string | null;
            /** Fecha Fin Vigencia */
            fecha_fin_vigencia: string | null;
            /** Nro Actual */
            nro_actual: number;
            /** Nro Fin */
            nro_fin: number;
            /** Activo */
            activo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TimbradoEmisionIn */
        TimbradoEmisionIn: {
            /**
             * Sucursal Id
             * Format: uuid
             */
            sucursal_id: string;
            /** Numero Timbrado */
            numero_timbrado: string;
            /** Punto Establecimiento */
            punto_establecimiento: string;
            /** Punto Expedicion */
            punto_expedicion: string;
            /** Fecha Inicio Vigencia */
            fecha_inicio_vigencia?: string | null;
            /** Fecha Fin Vigencia */
            fecha_fin_vigencia?: string | null;
            /** Nro Actual */
            nro_actual: number;
            /** Nro Fin */
            nro_fin: number;
            /**
             * Activo
             * @default true
             */
            activo: boolean;
        };
        /** TimbradoEmisionUpdate */
        TimbradoEmisionUpdate: {
            /** Numero Timbrado */
            numero_timbrado?: string | null;
            /** Punto Establecimiento */
            punto_establecimiento?: string | null;
            /** Punto Expedicion */
            punto_expedicion?: string | null;
            /** Fecha Inicio Vigencia */
            fecha_inicio_vigencia?: string | null;
            /** Fecha Fin Vigencia */
            fecha_fin_vigencia?: string | null;
            /** Nro Actual */
            nro_actual?: number | null;
            /** Nro Fin */
            nro_fin?: number | null;
            /** Activo */
            activo?: boolean | null;
        };
        /** TurnoCajaOut */
        TurnoCajaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Usuario Id */
            usuario_id: number;
            /**
             * Sucursal Id
             * Format: uuid
             */
            sucursal_id: string;
            /**
             * Fecha Apertura
             * Format: date-time
             */
            fecha_apertura: string;
            /** Fecha Cierre */
            fecha_cierre: string | null;
            /** Monto Apertura */
            monto_apertura: string;
            /** Monto Cierre Declarado */
            monto_cierre_declarado: string | null;
            /** Monto Cierre Sistema */
            monto_cierre_sistema: string | null;
            /** Diferencia */
            diferencia: string | null;
            /** Estado */
            estado: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TurnoCajaIn */
        TurnoCajaIn: {
            /**
             * Sucursal Id
             * Format: uuid
             */
            sucursal_id: string;
            /**
             * Monto Apertura
             * @default 0
             */
            monto_apertura: number | string;
        };
        /** TurnoCierreIn */
        TurnoCierreIn: {
            /** Monto Cierre Declarado */
            monto_cierre_declarado: number | string;
        };
        /** VentaItemOut */
        VentaItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad */
            cantidad: string;
            /** Precio Unitario */
            precio_unitario: string;
            /** Porcentaje Iva */
            porcentaje_iva: number;
            /** Subtotal */
            subtotal: string;
        };
        /** VentaOut */
        VentaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Turno Id
             * Format: uuid
             */
            turno_id: string;
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /** Timbrado Id */
            timbrado_id: string | null;
            /** Nro Factura Completo */
            nro_factura_completo: string | null;
            /** Condicion Venta */
            condicion_venta: string;
            /** Total Exenta */
            total_exenta: string;
            /** Total Iva5 */
            total_iva5: string;
            /** Total Iva10 */
            total_iva10: string;
            /** Total Final */
            total_final: string;
            /**
             * Fecha Emision
             * Format: date-time
             */
            fecha_emision: string;
            /** Estado */
            estado: string;
            /** Sincronizado */
            sincronizado: boolean;
            /** Items */
            items: components["schemas"]["VentaItemOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** VentaIn */
        VentaIn: {
            /**
             * Turno Id
             * Format: uuid
             */
            turno_id: string;
            /**
             * Cliente Id
             * Format: uuid
             */
            cliente_id: string;
            /** Timbrado Id */
            timbrado_id?: string | null;
            /**
             * Condicion Venta
             * @default CONTADO
             */
            condicion_venta: string;
            /** Items */
            items: components["schemas"]["VentaItemIn"][];
        };
        /** VentaItemIn */
        VentaItemIn: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad */
            cantidad: number | string;
            /** Precio Unitario */
            precio_unitario: number | string;
            /**
             * Porcentaje Iva
             * @default 10
             */
            porcentaje_iva: number;
        };
        /** MovCajaOut */
        MovCajaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Turno Id
             * Format: uuid
             */
            turno_id: string;
            /** Tipo Movimiento */
            tipo_movimiento: string;
            /** Concepto */
            concepto: string;
            /** Monto */
            monto: string;
            /** Venta Origen Id */
            venta_origen_id: string | null;
            /** Compra Origen Id */
            compra_origen_id: string | null;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MovCajaIn */
        MovCajaIn: {
            /**
             * Turno Id
             * Format: uuid
             */
            turno_id: string;
            /** Tipo Movimiento */
            tipo_movimiento: string;
            /**
             * Concepto
             * @default
             */
            concepto: string;
            /** Monto */
            monto: number | string;
        };
        /** CompraOut */
        CompraOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Turno Id */
            turno_id: string | null;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Fecha Emision */
            fecha_emision: string | null;
            /**
             * Fecha Recepcion
             * Format: date-time
             */
            fecha_recepcion: string;
            /** Total Costo */
            total_costo: string;
            /** Estado */
            estado: string;
            /** Detalles */
            detalles: components["schemas"]["DetalleCompraOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DetalleCompraOut */
        DetalleCompraOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad */
            cantidad: string;
            /** Costo Unitario */
            costo_unitario: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompraIn */
        CompraIn: {
            /** Turno Id */
            turno_id?: string | null;
            /**
             * Proveedor Id
             * Format: uuid
             */
            proveedor_id: string;
            /** Fecha Emision */
            fecha_emision?: string | null;
            /** Detalles */
            detalles: components["schemas"]["DetalleCompraIn"][];
        };
        /** DetalleCompraIn */
        DetalleCompraIn: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad */
            cantidad: number | string;
            /** Costo Unitario */
            costo_unitario: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    token_obtain_pair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPairOutputSchema"];
                };
            };
        };
    };
    token_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshOutputSchema"];
                };
            };
        };
    };
    token_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyInputSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schema"];
                };
            };
        };
    };
    core_api_list_sucursales: {
        parameters: {
            query?: {
                activo?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SucursalOut"][];
                };
            };
        };
    };
    core_api_create_sucursal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SucursalIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SucursalOut"];
                };
            };
        };
    };
    core_api_get_sucursal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sucursal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SucursalOut"];
                };
            };
        };
    };
    core_api_update_sucursal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sucursal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SucursalUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SucursalOut"];
                };
            };
        };
    };
    core_api_delete_sucursal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sucursal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_list_personas: {
        parameters: {
            query?: {
                es_cliente?: boolean | null;
                es_proveedor?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"][];
                };
            };
        };
    };
    core_api_create_persona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
        };
    };
    core_api_get_persona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
        };
    };
    core_api_update_persona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
        };
    };
    core_api_delete_persona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_api_list_marcas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaOut"][];
                };
            };
        };
    };
    catalog_api_create_marca: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcaIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaOut"];
                };
            };
        };
    };
    catalog_api_get_marca: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                marca_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcaOut"];
                };
            };
        };
    };
    catalog_api_delete_marca: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                marca_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_api_list_categorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaOut"][];
                };
            };
        };
    };
    catalog_api_create_categoria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaOut"];
                };
            };
        };
    };
    catalog_api_get_categoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaOut"];
                };
            };
        };
    };
    catalog_api_delete_categoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_api_list_sabores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaborOut"][];
                };
            };
        };
    };
    catalog_api_create_sabor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaborIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaborOut"];
                };
            };
        };
    };
    catalog_api_get_sabor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sabor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaborOut"];
                };
            };
        };
    };
    catalog_api_delete_sabor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sabor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_api_list_productos: {
        parameters: {
            query?: {
                activo?: boolean | null;
                marca_id?: string | null;
                categoria_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoOut"][];
                };
            };
        };
    };
    catalog_api_create_producto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoOut"];
                };
            };
        };
    };
    catalog_api_get_producto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoOut"];
                };
            };
        };
    };
    catalog_api_update_producto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoOut"];
                };
            };
        };
    };
    catalog_api_delete_producto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_api_search_by_barcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoOut"];
                };
            };
        };
    };
    catalog_api_list_codigos_barra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodigoBarraOut"][];
                };
            };
        };
    };
    catalog_api_create_codigo_barra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodigoBarraIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodigoBarraOut"];
                };
            };
        };
    };
    catalog_api_delete_codigo_barra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo_barra_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inventory_api_list_stock_by_sucursal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sucursal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSucursalOut"][];
                };
            };
        };
    };
    inventory_api_create_or_update_stock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockSucursalIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSucursalOut"];
                };
            };
        };
    };
    inventory_api_update_stock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockSucursalUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSucursalOut"];
                };
            };
        };
    };
    inventory_api_list_traslados: {
        parameters: {
            query?: {
                estado?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrasladoOut"][];
                };
            };
        };
    };
    inventory_api_get_traslado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traslado_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrasladoOut"];
                };
            };
        };
    };
    inventory_api_enviar_traslado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrasladoIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrasladoOut"];
                };
            };
        };
    };
    inventory_api_recibir_traslado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traslado_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrasladoRecepcionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrasladoOut"];
                };
            };
        };
    };
    billing_api_list_timbrados: {
        parameters: {
            query?: {
                activo?: boolean | null;
                sucursal_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimbradoEmisionOut"][];
                };
            };
        };
    };
    billing_api_create_timbrado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimbradoEmisionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimbradoEmisionOut"];
                };
            };
        };
    };
    billing_api_get_timbrado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timbrado_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimbradoEmisionOut"];
                };
            };
        };
    };
    billing_api_update_timbrado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timbrado_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimbradoEmisionUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimbradoEmisionOut"];
                };
            };
        };
    };
    pos_api_list_turnos: {
        parameters: {
            query?: {
                sucursal_id?: string | null;
                estado?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoCajaOut"][];
                };
            };
        };
    };
    pos_api_get_turno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turno_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoCajaOut"];
                };
            };
        };
    };
    pos_api_abrir_turno: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnoCajaIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoCajaOut"];
                };
            };
        };
    };
    pos_api_cerrar_turno: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turno_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnoCierreIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoCajaOut"];
                };
            };
        };
    };
    pos_api_list_ventas: {
        parameters: {
            query?: {
                turno_id?: string | null;
                estado?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentaOut"][];
                };
            };
        };
    };
    pos_api_crear_venta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VentaIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentaOut"];
                };
            };
        };
    };
    pos_api_get_venta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venta_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentaOut"];
                };
            };
        };
    };
    pos_api_anular_venta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venta_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentaOut"];
                };
            };
        };
    };
    pos_api_list_movimientos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turno_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovCajaOut"][];
                };
            };
        };
    };
    pos_api_create_movimiento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovCajaIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovCajaOut"];
                };
            };
        };
    };
    logistics_api_list_compras: {
        parameters: {
            query?: {
                estado?: string | null;
                proveedor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompraOut"][];
                };
            };
        };
    };
    logistics_api_crear_compra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompraIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompraOut"];
                };
            };
        };
    };
    logistics_api_get_compra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compra_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompraOut"];
                };
            };
        };
    };
}
